name: Build BW16 Firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Setup Arduino core for BW16
      run: |
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek.com_amebad_index.json
        arduino-cli core update-index
        arduino-cli core install realtek:amebad

    - name: Build firmware
      run: |
        arduino-cli compile \
          --fqbn realtek:amebad:BW16 \
          BW16_Test.ino

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: BW16_BIN
        path: |
          **/*.bin
