name: Build BW16 Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:mbed

      - name: Compile
        run: |
          arduino-cli compile --fqbn arduino:mbed:rtl8720dn bw16v1.ino

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: BW16_BIN
          path: build/**/*        uses: actions/upload-artifact@v4
        with:
          name: BW16_BIN
          path: build/**/**/*.bin        uses: actions/upload-artifact@v4
        with:
          name: BW16_BIN
          path: build/**/**/*.bin
